[project]
name = "worldvision-ai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "김가연", email = "yoni0345678910@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.4",
    "python-multipart>=0.0.32",
    "python-dotenv>=1.0.0",
    "openai>=1.0.0",
    "pydantic>=2.0.0",
    "langchain>=0.3.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.0",
    "langchain-openai>=1.6.0",
    "langchain-postgres>=0.0.17",
    "psycopg2-binary>=2.9.12",
    "pgvector>=0.2.0",
    "pypdf>=6.16.2",
]

[project.scripts]
worldvision-ai-project = "worldvision_ai_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
